version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    links:
      - mongo
  frontend:
    build: ./frontend
    hostname: 127.0.0.1
    ports:
      - '3000:3000'
  mongo:
    image: mongo
    ports:
      - '27017:27017'